-- 1) 기존 값 + 새 값을 모두 허용하도록 확장
ALTER TABLE member
MODIFY COLUMN user_type ENUM(
    'FAMILY_OR_SUPPORTER','MOTHER','PROFESSIONAL',  -- 기존 값 (실제 값으로 교체)
    'NO_CHILD_PLAN','PREPARING_FOR_PREGNANCY','PREGNANT','RAISING_CHILDREN'
) NOT NULL;

-- 2) 데이터 변환
UPDATE member SET user_type = 'RAISING_CHILDREN' WHERE user_type = 'MOTHER';
UPDATE member SET user_type = 'NO_CHILD_PLAN' WHERE user_type IN ('FAMILY_OR_SUPPORTER', 'PROFESSIONAL');

-- 3) 새 ENUM으로 축소
ALTER TABLE member
MODIFY COLUMN user_type ENUM(
    'NO_CHILD_PLAN','PREPARING_FOR_PREGNANCY','PREGNANT','RAISING_CHILDREN'
) NOT NULL;
